Adjust SVG Viewbox to contain whole letter
adobe-type-tools/opentype-svg pull request #23
Opened 2021-05-22 22:32 UTC by davidgodzsak

SVG ViewBox originally contained glyphs from the baseline, with a `-av` flag this can now be changed to also include the descender and lineGap.

2021-05-24 16:54 UTC, miguelsousa requested changes
In addition to the inline comments, there are several code formatting problems. See the CI errors, or use flake8 locally.

2021-05-24 16:54 UTC, miguelsousa commented on lib/opentypesvg/fonts2svg.py
> +    viewbox = viewbox_settings(font_paths_list, options)
Pass only the first font, and only the option that matters.

2021-05-24 16:54 UTC, miguelsousa commented on lib/opentypesvg/fonts2svg.py
> +            y = -hhea.ascender
Use the x/yMin/Max values from the `head` table instead.

2021-05-24 16:54 UTC, miguelsousa commented on lib/opentypesvg/fonts2svg.py
> +            y = -hhea.ascender
Also, only one try/except is needed; move the if/else branching to the inside of it.

2021-05-24 16:54 UTC, miguelsousa commented on lib/opentypesvg/fonts2svg.py
> +        help="adjust the viewbox to the glyph (descender calculated and lineGap in height)."
This description is confusing. What about "vertically center the viewBox on the bounding box of all glyphs" ?

2021-05-24 22:10 UTC, davidgodzsak commented
After some manual testing, I noticed that `head.yMin` possibly denotes the bottom of the bounding box for a glyph and `yMax` the top while in SVG it is the other way around, hence `y = -head.yMax`.

2021-05-25 05:26 UTC, miguelsousa requested changes
> I noticed that `head.yMin` possibly denotes the bottom of the bounding box for a glyph and `yMax` the top while in SVG it is the other way around

Right, [in SVG the coordinate system is `y-down`](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Positions#the_grid) whereas the font's is the common `y-up`.

> hence `y = -head.yMax`

I think you'll have to factor `head.yMin` somewhere because if the font has a `head.yMin` value grater than zero the glyphs won't be centered nor scaled as expected. I made these two edge-case fonts to help you test.

[font_registerd.ttf.zip](https://github.com/adobe-type-tools/opentype-svg/files/6536718/font_registerd.ttf.zip)
[font_trademark.ttf.zip](https://github.com/adobe-type-tools/opentype-svg/files/6536720/font_trademark.ttf.zip)

2021-05-25 05:26 UTC, miguelsousa commented on tests/fonts2svg_test.py
> +def test_adjust_to_viewbox_default(base_font_path, capsys):
You can remove `capsys` on both tests.

2021-05-25 07:07 UTC, davidgodzsak commented
> I think you'll have to factor `head.yMin` somewhere because if the font has a `head.yMin` value grater than zero the glyphs won't be centered nor scaled as expected. I made these two edge-case fonts to help you test.

I already have them factored in the:  `height = head.yMax + abs(head.yMin)`.  I think this is an solution for the y-up -y-down problem together with having -yMax as the top

2021-05-26 03:55 UTC, miguelsousa requested changes
As far as I can tell, you've got the values of `x` and `y` nailed, but `width` and `height` need some tweaks.

With the current code, the SVG that will come out of **[font_registerd.ttf](https://github.com/adobe-type-tools/opentype-svg/files/6536718/font_registerd.ttf.zip)** is this,
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="23 -713 423 1032">
	<path fill="#000000" d="M211 -319Q160 -319 117 -344Q74 -369 48.5 -413.5Q23 -458 23 -516Q23 -575 48.5 -619Q74 -663 117 -688Q160 -713 211 -713Q263 -713 306 -688Q349 -663 374.5 -619Q400 -575 400 -516Q400 -458 374.5 -413.5Q349 -369 306 -344Q263 -319 211 -319ZM211 -356Q253 -356 286.5 -376Q320 -396 340 -432.5Q360 -469 360 -516Q360 -563 340 -599.5Q320 -636 286.5 -656.5Q253 -677 211 -677Q169 -677 135.5 -656.5Q102 -636 82.5 -599.5Q63 -563 63 -516Q63 -469 82.5 -432.5Q102 -396 135.5 -376Q169 -356 211 -356ZM139 -417V-620H215Q247 -620 270 -605.5Q293 -591 293 -555Q293 -537 283 -521.5Q273 -506 256 -500L302 -417H256L221 -487H180V-417ZM180 -519H206Q249 -519 249 -553Q249 -568 240 -577Q231 -586 208 -586H180Z"/>
</svg>
```
but the correct `viewBox` should be,

    "23 -713 377 394"

since it makes the SVG's boundaries be snug to the glyph.

---
If made a set of 11 test fonts that you can find inside this ZIP file: [fixtures.zip](https://github.com/adobe-type-tools/opentype-svg/files/6543689/fixtures.zip). Please add them to this PR, placing them inside a folder named **fixtures** which should be placed inside the existing **tests** folder.

Also add this snippet to **conftest.py**,
```python
@pytest.fixture
def fixtures_dir():
    yield os.path.join(os.path.dirname(__file__), 'fixtures')
```
and update the `test_adjust_to_viewbox` method to this,
```python
import os
import pytest


@pytest.mark.parametrize('file_name, expected', [
    ("1.ttf", "309 -1108 360 638"),
    ("2.ttf", "-904 -1110 416 650"),
    ("3.ttf", "-824 310 420 662"),
    ("4.ttf", "197 342 452 638"),
    ("12.ttf", "-904 -1110 1573 650"),
    ("13.ttf", "-824 -1108 1493 2080"),
    ("14.ttf", "197 -1108 472 2088"),
    ("23.ttf", "-904 -1110 500 2082"),
    ("24.ttf", "-904 -1110 1553 2090"),
    ("34.ttf", "-824 310 1473 670"),
    ("1234.ttf", "-904 -1110 1573 2090"),
])
def test_adjust_to_viewbox(file_name, expected, fixtures_dir):
    font_path = os.path.join(fixtures_dir, file_name)
    viewbox = viewbox_settings(font_path, True)
    assert viewbox == expected
```

I haven't had time to determine what changes are needed to produce the `width` and `height` values above, but I can assure you that they're correct.

2021-05-26 12:27 UTC, davidgodzsak commented
But wouldn't I need the `hhea` table to get the `ascend`, `descend`, `linegap` to calculate the height and `xMaxExtent` or similar to get the `width` liek I did in the first iteration?

2021-05-26 16:43 UTC, miguelsousa commented
> the tables in ttf tell you information about the whole font and not the glyphs themselves

Yes, the x/yMin/Max values in the`head` table define the combined bounding box of all glyphs in the font, not the bounding box of each individual glyph.

> With this, the borders won't snuggle the glyph

Right, in a common font they likely won't because usually not all glyphs will have the same bounding box.
But in the case of the test fonts, each of them has a single glyph, so the font's bbox will certainly match the glyph's. I did this to make it easy to validate the viewBox calculations.

> If the desired effect is to snuggle the fonts then that has to be dynamically calculated for every glyph.

For me, the goal of the new `-av` option is to make the tool output the SVGs with a viewBox that encloses all of the glyphs in the font. The viewBox value will be the same for all SVGs, and all the glyphs will be fully visible (as opposed to the default behavior which makes a "view window" of 1000x1000 edge-aligned at 0,0).

2021-05-30 19:09 UTC, davidgodzsak commented
@miguelsousa I think I got it this time, thanks for all the help!

2021-06-01 01:07 UTC, miguelsousa approved these changes
👍 Thanks for contributing this functionality.

2021-06-01 01:09 UTC, merged